### ISSUE TITLE
MonitoredMiddleware crashes if probe is not present

### ISSUE THREAD

**Issue by Pixelshaped** [blackfireio/php-sdk#71]
Following the configuration

```
framework:
  messenger:
    buses:
      messenger.bus.default:
        middleware:
          - 'Blackfire\Bridge\Symfony\MonitoredMiddleware'

services:
  Blackfire\Bridge\Symfony\MonitoredMiddleware: ~
```

I've got a crash in `MonitoredMiddleware` at line 32: `Class "BlackfireProbe" not found.`

And it's true: on my local machine, I don't have the probe installed.

I fixed it by adding
```
when@prod:
```
